USE [master]
GO

/****** Object:  Database [CompanyOrderManagementDb]    Script Date: 23.02.2023 23:52:20 ******/
CREATE DATABASE [CompanyOrderManagementDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CompanyOrderManagementDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CompanyOrderManagementDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CompanyOrderManagementDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CompanyOrderManagementDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompanyOrderManagementDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET RECOVERY FULL 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET  MULTI_USER 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompanyOrderManagementDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CompanyOrderManagementDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CompanyOrderManagementDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [CompanyOrderManagementDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CompanyOrderManagementDb] SET  READ_WRITE 
GO

